<?xml version="1.0"?>
<robot name="sixdof_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_length" value="0.01" />
    <xacro:property name="lidar_width" value="0.1" />
    <xacro:property name="lidar_height" value="0.05" />
    <xacro:property name="m" value="0.1" />
    
    <link name="lidar_link">
        <visual>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}" />
            </geometry>

        </visual>

        <collision>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${m}" />
            <inertia ixx="${(m/12) * (lidar_height*lidar_height + lidar_length*lidar_length)}" ixy="0" ixz="0"
                     iyy="${(m/12) * (lidar_width*lidar_width + lidar_length*lidar_length)}"  iyz="0"
                     izz="${(m/12) * (lidar_width*lidar_width + lidar_height*lidar_height)}" />
        </inertial>  

    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0.15 0 ${lidar_height/2}" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_link">
        <sensor name="lidar_sensor" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>180</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.5708</min_angle>
                        <max_angle>1.5708</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>2.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <plugin name="lidar" filename="libgazebo_ros_ray_sensor.so">
                <frame_name>lidar_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>
